"""Create projects and activities tables

Revision ID: e349ab7b547e
Revises:
Create Date: 2026-07-27 00:29:58.296976

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e349ab7b547e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("bac", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("planned_progress", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("actual_progress", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("ac", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ac >= 0", name=op.f("ck_activities_ac_non_negative")),
        sa.CheckConstraint(
            "actual_progress BETWEEN 0 AND 100",
            name=op.f("ck_activities_actual_progress_within_range"),
        ),
        sa.CheckConstraint("bac > 0", name=op.f("ck_activities_bac_positive")),
        sa.CheckConstraint(
            "planned_progress BETWEEN 0 AND 100",
            name=op.f("ck_activities_planned_progress_within_range"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_activities_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index(op.f("ix_activities_project_id"), "activities", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activities_project_id"), table_name="activities")
    op.drop_table("activities")
    op.drop_table("projects")
    # ### end Alembic commands ###
